import { normalizePathologySearch } from './pathologySearch'

export type TranslationStatus = 'curated' | 'assisted' | 'source-only'

export type IcdoTranslation = {
  text: string
  status: TranslationStatus
}

const EXACT: Record<string, string> = {
  'neoplasm, benign': 'Tân sinh lành tính',
  'neoplasm, uncertain whether benign or malignant': 'Tân sinh chưa xác định lành tính hay ác tính',
  'neoplasm, malignant, nos': 'Tân sinh ác tính, không định loại khác (NOS)',
  'neoplasm, metastatic': 'Tân sinh di căn',
  'neoplasm, malignant, uncertain whether primary or metastatic': 'Tân sinh ác tính, chưa xác định nguyên phát hay di căn',
  'adenocarcinoma, nos': 'Ung thư biểu mô tuyến, không định loại khác (NOS)',
  'squamous cell carcinoma, nos': 'Ung thư biểu mô tế bào vảy, không định loại khác (NOS)',
  'basal cell carcinoma, nos': 'Ung thư biểu mô tế bào đáy, không định loại khác (NOS)',
  'basal cell tumour': 'U tế bào đáy',
  'pigmented basal cell carcinoma': 'Ung thư biểu mô tế bào đáy sắc tố',
  'basal cell carcinoma with adnexal differentiation': 'Ung thư biểu mô tế bào đáy biệt hóa phần phụ da',
  'superficial basal cell carcinoma': 'Ung thư biểu mô tế bào đáy thể nông',
  'multifocal superficial basal cell carcinoma': 'Ung thư biểu mô tế bào đáy thể nông đa ổ',
  'infiltrating basal cell carcinoma, nos': 'Ung thư biểu mô tế bào đáy thể thâm nhiễm, không định loại khác (NOS)',
  'infiltrating basal cell carcinoma, non-sclerosing': 'Ung thư biểu mô tế bào đáy thể thâm nhiễm, không xơ hóa',
  'basal cell carcinoma, sclerosing/morphoeic': 'Ung thư biểu mô tế bào đáy thể xơ hóa/dạng xơ cứng',
  'basal cell carcinoma, sarcomatoid': 'Ung thư biểu mô tế bào đáy dạng sarcoma',
  'basosquamous carcinoma': 'Ung thư biểu mô đáy-vảy',
  'basal cell carcinoma, nodular': 'Ung thư biểu mô tế bào đáy thể nốt',
  'basal cell carcinoma, micronodular': 'Ung thư biểu mô tế bào đáy thể vi nốt',
  'hepatocellular carcinoma, nos': 'Ung thư biểu mô tế bào gan, không định loại khác (NOS)',
  'renal cell carcinoma, nos': 'Ung thư biểu mô tế bào thận, không định loại khác (NOS)',
  'urothelial carcinoma, nos': 'Ung thư biểu mô niệu mạc, không định loại khác (NOS)',
  'papillary thyroid carcinoma, nos': 'Ung thư biểu mô tuyến giáp thể nhú, không định loại khác (NOS)',
  'papillary thyroid carcinoma': 'Ung thư biểu mô tuyến giáp thể nhú',
  'follicular thyroid carcinoma': 'Ung thư biểu mô tuyến giáp thể nang',
  'medullary thyroid carcinoma': 'Ung thư biểu mô tuyến giáp thể tủy',
  'anaplastic thyroid carcinoma': 'Ung thư biểu mô tuyến giáp không biệt hóa',
  'non-invasive follicular thyroid neoplasm with papillary-like nuclear features': 'Tân sinh tuyến giáp dạng nang không xâm nhập với đặc điểm nhân dạng nhú (NIFTP)',
  'invasive breast carcinoma of no special type': 'Ung thư biểu mô vú xâm nhập không thuộc típ đặc biệt',
  'infiltrating duct carcinoma, nos': 'Ung thư biểu mô ống xâm nhập, không định loại khác (NOS)',
  'ductal carcinoma in situ, nos': 'Ung thư biểu mô ống tại chỗ, không định loại khác (NOS)',
  'lobular carcinoma in situ, nos': 'Tân sinh tiểu thùy tại chỗ, không định loại khác (NOS)',
  'invasive lobular carcinoma, nos': 'Ung thư biểu mô tiểu thùy xâm nhập, không định loại khác (NOS)',
  'small cell carcinoma, nos': 'Ung thư biểu mô tế bào nhỏ, không định loại khác (NOS)',
  'large cell neuroendocrine carcinoma': 'Ung thư biểu mô thần kinh nội tiết tế bào lớn',
  'neuroendocrine tumour, nos': 'U thần kinh nội tiết, không định loại khác (NOS)',
  'neuroendocrine carcinoma, nos': 'Ung thư biểu mô thần kinh nội tiết, không định loại khác (NOS)',
  'gastrointestinal stromal tumour': 'U mô đệm đường tiêu hóa',
  'gastrointestinal stromal tumour, nos': 'U mô đệm đường tiêu hóa, không định loại khác (NOS)',
  'diffuse large b-cell lymphoma, nos': 'U lympho tế bào B lớn lan tỏa, không định loại khác (NOS)',
  'follicular lymphoma, nos': 'U lympho thể nang, không định loại khác (NOS)',
  'mantle cell lymphoma': 'U lympho tế bào vùng áo',
  'marginal zone lymphoma, nos': 'U lympho vùng rìa, không định loại khác (NOS)',
  'classical hodgkin lymphoma': 'U lympho Hodgkin kinh điển',
  'glioblastoma, nos': 'U nguyên bào thần kinh đệm, không định loại khác (NOS)',
  'meningioma, nos': 'U màng não, không định loại khác (NOS)',
  'schwannoma, nos': 'U bao Schwann, không định loại khác (NOS)',
  'leiomyoma, nos': 'U cơ trơn, không định loại khác (NOS)',
  'leiomyosarcoma, nos': 'Sarcoma cơ trơn, không định loại khác (NOS)',
  'lipoma, nos': 'U mỡ, không định loại khác (NOS)',
  'liposarcoma, nos': 'Sarcoma mỡ, không định loại khác (NOS)',
  'osteosarcoma, nos': 'Sarcoma xương, không định loại khác (NOS)',
  'chondrosarcoma, nos': 'Sarcoma sụn, không định loại khác (NOS)',
  'rhabdomyosarcoma, nos': 'Sarcoma cơ vân, không định loại khác (NOS)',
  'angiosarcoma, nos': 'Sarcoma mạch, không định loại khác (NOS)',
  'melanoma, nos': 'U hắc tố ác tính, không định loại khác (NOS)',
  'clear cell carcinoma, nos': 'Ung thư biểu mô tế bào sáng, không định loại khác (NOS)',
  'mucinous adenocarcinoma, nos': 'Ung thư biểu mô tuyến dạng nhầy, không định loại khác (NOS)',
  'endometrioid carcinoma, nos': 'Ung thư biểu mô dạng nội mạc tử cung, không định loại khác (NOS)',
  'serous carcinoma, nos': 'Ung thư biểu mô thanh dịch, không định loại khác (NOS)',
  'carcinosarcoma, nos': 'Ung thư biểu mô-sarcoma, không định loại khác (NOS)',
  'external upper lip': 'Phần ngoài môi trên',
  'external lower lip': 'Phần ngoài môi dưới',
  'external lip, nos': 'Phần ngoài môi, không định vị khác (NOS)',
  'mucosa of upper lip': 'Niêm mạc môi trên',
  'mucosa of lower lip': 'Niêm mạc môi dưới',
  'mucosa of lip, nos': 'Niêm mạc môi, không định vị khác (NOS)',
  'commissure of lip': 'Mép môi',
  'lip, nos': 'Môi, không định vị khác (NOS)',
  'base of tongue, nos': 'Đáy lưỡi, không định vị khác (NOS)',
  'tongue, nos': 'Lưỡi, không định vị khác (NOS)',
  'parotid gland': 'Tuyến mang tai',
  'submandibular gland': 'Tuyến dưới hàm',
  'sublingual gland': 'Tuyến dưới lưỡi',
  'oesophagus, nos': 'Thực quản, không định vị khác (NOS)',
  'stomach, nos': 'Dạ dày, không định vị khác (NOS)',
  'cardia, nos': 'Tâm vị, không định vị khác (NOS)',
  'fundus of stomach': 'Đáy vị',
  'body of stomach': 'Thân vị',
  'gastric antrum': 'Hang vị',
  'pylorus': 'Môn vị',
  'small intestine, nos': 'Ruột non, không định vị khác (NOS)',
  'caecum': 'Manh tràng',
  'appendix': 'Ruột thừa',
  'colon, nos': 'Đại tràng, không định vị khác (NOS)',
  'rectum, nos': 'Trực tràng, không định vị khác (NOS)',
  'anus, nos': 'Hậu môn, không định vị khác (NOS)',
  'liver': 'Gan',
  'intrahepatic bile duct': 'Đường mật trong gan',
  'gallbladder': 'Túi mật',
  'pancreas, nos': 'Tụy, không định vị khác (NOS)',
  'larynx, nos': 'Thanh quản, không định vị khác (NOS)',
  'trachea': 'Khí quản',
  'main bronchus': 'Phế quản chính',
  'upper lobe, lung': 'Thùy trên phổi',
  'middle lobe, lung': 'Thùy giữa phổi',
  'lower lobe, lung': 'Thùy dưới phổi',
  'lung, nos': 'Phổi, không định vị khác (NOS)',
  'bone, nos': 'Xương, không định vị khác (NOS)',
  'skin, nos': 'Da, không định vị khác (NOS)',
  'breast, nos': 'Vú, không định vị khác (NOS)',
  'nipple': 'Núm vú',
  'central portion of breast': 'Vùng trung tâm của vú',
  'upper-inner quadrant of breast': 'Một phần tư trên-trong của vú',
  'lower-inner quadrant of breast': 'Một phần tư dưới-trong của vú',
  'upper-outer quadrant of breast': 'Một phần tư trên-ngoài của vú',
  'lower-outer quadrant of breast': 'Một phần tư dưới-ngoài của vú',
  'cervix uteri': 'Cổ tử cung',
  'corpus uteri': 'Thân tử cung',
  'uterus, nos': 'Tử cung, không định vị khác (NOS)',
  'ovary': 'Buồng trứng',
  'vagina, nos': 'Âm đạo, không định vị khác (NOS)',
  'vulva, nos': 'Âm hộ, không định vị khác (NOS)',
  'prostate gland': 'Tuyến tiền liệt',
  'testis, nos': 'Tinh hoàn, không định vị khác (NOS)',
  'kidney, nos': 'Thận, không định vị khác (NOS)',
  'renal pelvis': 'Bể thận',
  'ureter': 'Niệu quản',
  'bladder, nos': 'Bàng quang, không định vị khác (NOS)',
  'brain, nos': 'Não, không định vị khác (NOS)',
  'thyroid gland': 'Tuyến giáp',
  'adrenal gland, nos': 'Tuyến thượng thận, không định vị khác (NOS)',
  'lymph node, nos': 'Hạch lympho, không định vị khác (NOS)',
  'unknown primary site': 'Không rõ vị trí nguyên phát',
}

const REPLACEMENTS: Array<[RegExp, string]> = [
  [/uncertain whether benign or malignant/gi, 'chưa xác định lành tính hay ác tính'],
  [/uncertain malignant potential/gi, 'tiềm năng ác tính chưa xác định'],
  [/non-invasive/gi, 'không xâm nhập'],
  [/poorly differentiated/gi, 'biệt hóa kém'],
  [/well differentiated/gi, 'biệt hóa rõ'],
  [/high[- ]grade/gi, 'độ cao'],
  [/low[- ]grade/gi, 'độ thấp'],
  [/squamous cell carcinoma/gi, 'ung thư biểu mô tế bào vảy'],
  [/basal cell carcinoma/gi, 'ung thư biểu mô tế bào đáy'],
  [/hepatocellular carcinoma/gi, 'ung thư biểu mô tế bào gan'],
  [/renal cell carcinoma/gi, 'ung thư biểu mô tế bào thận'],
  [/urothelial carcinoma/gi, 'ung thư biểu mô niệu mạc'],
  [/neuroendocrine carcinoma/gi, 'ung thư biểu mô thần kinh nội tiết'],
  [/neuroendocrine tumour/gi, 'u thần kinh nội tiết'],
  [/neuroendocrine tumor/gi, 'u thần kinh nội tiết'],
  [/adenocarcinoma/gi, 'ung thư biểu mô tuyến'],
  [/carcinoma/gi, 'ung thư biểu mô'],
  [/gastrointestinal stromal tumour/gi, 'u mô đệm đường tiêu hóa'],
  [/gastrointestinal stromal tumor/gi, 'u mô đệm đường tiêu hóa'],
  [/diffuse large b-cell lymphoma/gi, 'u lympho tế bào B lớn lan tỏa'],
  [/hodgkin lymphoma/gi, 'u lympho Hodgkin'],
  [/lymphoma/gi, 'u lympho'],
  [/leiomyosarcoma/gi, 'sarcoma cơ trơn'],
  [/rhabdomyosarcoma/gi, 'sarcoma cơ vân'],
  [/liposarcoma/gi, 'sarcoma mỡ'],
  [/osteosarcoma/gi, 'sarcoma xương'],
  [/chondrosarcoma/gi, 'sarcoma sụn'],
  [/angiosarcoma/gi, 'sarcoma mạch'],
  [/melanoma/gi, 'u hắc tố ác tính'],
  [/papillary/gi, 'dạng nhú'],
  [/follicular/gi, 'dạng nang'],
  [/mucinous/gi, 'dạng nhầy'],
  [/serous/gi, 'thanh dịch'],
  [/endometrioid/gi, 'dạng nội mạc tử cung'],
  [/clear cell/gi, 'tế bào sáng'],
  [/spindle cell/gi, 'tế bào hình thoi'],
  [/giant cell/gi, 'tế bào khổng lồ'],
  [/small cell/gi, 'tế bào nhỏ'],
  [/large cell/gi, 'tế bào lớn'],
  [/in situ/gi, 'tại chỗ'],
  [/invasive/gi, 'xâm nhập'],
  [/metastatic/gi, 'di căn'],
  [/malignant/gi, 'ác tính'],
  [/benign/gi, 'lành tính'],
  [/tumours/gi, 'các u'],
  [/tumors/gi, 'các u'],
  [/tumour/gi, 'u'],
  [/tumor/gi, 'u'],
  [/neoplasm/gi, 'tân sinh'],
  [/adenoma/gi, 'u tuyến'],
  [/sarcoma/gi, 'sarcoma'],
  [/upper lobe/gi, 'thùy trên'],
  [/middle lobe/gi, 'thùy giữa'],
  [/lower lobe/gi, 'thùy dưới'],
  [/lymph node/gi, 'hạch lympho'],
  [/bone marrow/gi, 'tủy xương'],
  [/soft tissue/gi, 'mô mềm'],
  [/bile duct/gi, 'đường mật'],
  [/salivary gland/gi, 'tuyến nước bọt'],
  [/urinary bladder/gi, 'bàng quang'],
  [/renal pelvis/gi, 'bể thận'],
  [/thyroid gland/gi, 'tuyến giáp'],
  [/adrenal gland/gi, 'tuyến thượng thận'],
  [/prostate gland/gi, 'tuyến tiền liệt'],
  [/uterine cervix/gi, 'cổ tử cung'],
  [/corpus uteri/gi, 'thân tử cung'],
  [/small intestine/gi, 'ruột non'],
  [/large intestine/gi, 'ruột già'],
  [/oesophagus/gi, 'thực quản'],
  [/esophagus/gi, 'thực quản'],
  [/stomach/gi, 'dạ dày'],
  [/colon/gi, 'đại tràng'],
  [/rectum/gi, 'trực tràng'],
  [/appendix/gi, 'ruột thừa'],
  [/liver/gi, 'gan'],
  [/pancreas/gi, 'tụy'],
  [/gallbladder/gi, 'túi mật'],
  [/lung/gi, 'phổi'],
  [/breast/gi, 'vú'],
  [/kidney/gi, 'thận'],
  [/ovary/gi, 'buồng trứng'],
  [/vagina/gi, 'âm đạo'],
  [/vulva/gi, 'âm hộ'],
  [/skin/gi, 'da'],
  [/brain/gi, 'não'],
  [/bone/gi, 'xương'],
  [/,?\s*nos\b/gi, ', không định loại khác (NOS)'],
  [/\btype\b/gi, 'típ'],
  [/\bof\b/gi, 'của'],
]

const ENGLISH_RESIDUE = /\b(the|with|without|cell|cells|gland|glands|lesion|disease|syndrome|associated|arising|specified|overlapping|portion|quadrant|wall|duct|lobe|cavity|pharynx|mouth|lip|tongue|palate|tonsil|nose|ear|eye|heart|pleura|peritoneum|mediastinum|testis|penis|ureter|bladder|urethra|placenta)\b/i

const sentenceCase = (value: string) => value
  ? value.charAt(0).toUpperCase() + value.slice(1)
  : value

export const translateIcdoTerm = (value: unknown): IcdoTranslation => {
  const original = String(value || '').trim()
  if (!original) return { text: '', status: 'source-only' }
  const exact = EXACT[original.toLowerCase()]
  if (exact) return { text: exact, status: 'curated' }

  let translated = original
  let replacementCount = 0
  for (const [pattern, replacement] of REPLACEMENTS) {
    const next = translated.replace(pattern, replacement)
    if (next !== translated) replacementCount += 1
    translated = next
  }
  translated = sentenceCase(translated.replace(/\s+/g, ' ').replace(/\s+,/g, ',').trim())
  if (replacementCount >= 2 && !ENGLISH_RESIDUE.test(translated) && normalizePathologySearch(translated) !== normalizePathologySearch(original)) {
    return { text: translated, status: 'assisted' }
  }
  return { text: '', status: 'source-only' }
}

export const icdoTranslationLabel = (status: TranslationStatus) => ({
  curated: 'Thuật ngữ Việt đã chuẩn hóa',
  assisted: 'Bản dịch hỗ trợ y khoa',
  'source-only': 'Giữ nguyên danh pháp WHO/IARC',
}[status])
