// Generated from NordiQC's public assessment index by scripts/sync-nordiqc-markers.mjs.
// Do not add local case metadata here. Clinical interpretation belongs in ihcMarkerAtlas.ts.

export interface IhcMarkerCatalogEntry {
  id: string
  name: string
  fullNameEn: string
  latestAssessment: string
  assessmentYear: string
  sourceUrl: string
  reportUrl: string
  protocolUrl?: string
}

export const NORDIQC_SOURCE = {
  organization: 'NordiQC',
  title: 'Immunohistochemical Quality Control - Assessments',
  url: 'https://www.nordiqc.org/epitope.php',
  syncedAt: '2026-09-02',
} as const

export const IHC_MARKER_CATALOG: IhcMarkerCatalogEntry[] = [
  {
    id: "14",
    name: "ALK (lung)",
    fullNameEn: "Anaplastic lymphoma kinase",
    latestAssessment: "Run 73",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=14",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/201_14.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=14",
  },
  {
    id: "13",
    name: "AMACR",
    fullNameEn: "α-methylacyl-CoA racemase",
    latestAssessment: "Run 75",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=13",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/205_13.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=13",
  },
  {
    id: "6",
    name: "ASMA",
    fullNameEn: "Alpha-Smooth Muscle Actin",
    latestAssessment: "Run 73",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=6",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/201_6.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=6",
  },
  {
    id: "116",
    name: "BAP1",
    fullNameEn: "BRCA1-Associated Protein 1",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=116",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_116.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=116",
  },
  {
    id: "16",
    name: "Bcl-2",
    fullNameEn: "Bcl-2 protein",
    latestAssessment: "Run 73",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=16",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/201_16.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=16",
  },
  {
    id: "17",
    name: "Bcl-6",
    fullNameEn: "Bcl-6 protein",
    latestAssessment: "Run 70",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=17",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/187_17.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=17",
  },
  {
    id: "113",
    name: "BRAF",
    fullNameEn: "BRAF V600E",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=113",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_113.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=113",
  },
  {
    id: "104",
    name: "C-MYC",
    fullNameEn: "C-MYC",
    latestAssessment: "Run 56",
    assessmentYear: "2019",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=104",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/120_104.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=104",
  },
  {
    id: "19",
    name: "CA125",
    fullNameEn: "Cancer Antigen 125",
    latestAssessment: "Run 29",
    assessmentYear: "2010",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=19",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/29_19.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=19",
  },
  {
    id: "18",
    name: "CALRET",
    fullNameEn: "Calretinin",
    latestAssessment: "Run 76",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=18",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/214_18.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=18",
  },
  {
    id: "23",
    name: "CD10",
    fullNameEn: "CD10",
    latestAssessment: "Run 68",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=23",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/172_23.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=23",
  },
  {
    id: "36",
    name: "CD117",
    fullNameEn: "CD117",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=36",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_36.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=36",
  },
  {
    id: "37",
    name: "CD138",
    fullNameEn: "CD138",
    latestAssessment: "Run 69",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=37",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/173_37.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=37",
  },
  {
    id: "24",
    name: "CD14",
    fullNameEn: "CD14",
    latestAssessment: "Run 11",
    assessmentYear: "2004",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=24",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/11_24.pdf",
  },
  {
    id: "25",
    name: "CD15",
    fullNameEn: "CD15",
    latestAssessment: "Run 61",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=25",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/145_25.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=25",
  },
  {
    id: "38",
    name: "CD163",
    fullNameEn: "CD163",
    latestAssessment: "Run 31",
    assessmentYear: "2011",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=38",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/31_38.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=38",
  },
  {
    id: "26",
    name: "CD19",
    fullNameEn: "CD19",
    latestAssessment: "Run 35",
    assessmentYear: "2012",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=26",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/35_26.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=26",
  },
  {
    id: "27",
    name: "CD20",
    fullNameEn: "CD20",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=27",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_27.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=27",
  },
  {
    id: "28",
    name: "CD23",
    fullNameEn: "CD23",
    latestAssessment: "Run 50",
    assessmentYear: "2017",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=28",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/89_28.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=28",
  },
  {
    id: "3",
    name: "CD3",
    fullNameEn: "CD3",
    latestAssessment: "Run 63",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=3",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/147_3.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=3",
  },
  {
    id: "5",
    name: "CD30",
    fullNameEn: "CD30",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=5",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_5.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=5",
  },
  {
    id: "29",
    name: "CD31",
    fullNameEn: "CD31",
    latestAssessment: "Run 62",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=29",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/146_29.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=29",
  },
  {
    id: "30",
    name: "CD34",
    fullNameEn: "CD34",
    latestAssessment: "Run 46",
    assessmentYear: "2016",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=30",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/79_30.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=30",
  },
  {
    id: "4",
    name: "CD4",
    fullNameEn: "CD4",
    latestAssessment: "Run 67",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=4",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/171_4.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=4",
  },
  {
    id: "31",
    name: "CD45",
    fullNameEn: "CD45",
    latestAssessment: "Run 59",
    assessmentYear: "2020",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=31",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/134_31.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=31",
  },
  {
    id: "21",
    name: "CD5",
    fullNameEn: "CD5",
    latestAssessment: "Run 69",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=21",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/173_21.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=21",
  },
  {
    id: "32",
    name: "CD56",
    fullNameEn: "CD56",
    latestAssessment: "Run 64",
    assessmentYear: "2022",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=32",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/158_32.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=32",
  },
  {
    id: "33",
    name: "CD68",
    fullNameEn: "CD68",
    latestAssessment: "Run 60",
    assessmentYear: "2020",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=33",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/136_33.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=33",
  },
  {
    id: "34",
    name: "CD79a",
    fullNameEn: "CD79a",
    latestAssessment: "Run 63",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=34",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/147_34.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=34",
  },
  {
    id: "22",
    name: "CD8",
    fullNameEn: "CD8",
    latestAssessment: "Run 72",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=22",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/189_22.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=22",
  },
  {
    id: "35",
    name: "CD99",
    fullNameEn: "CD99",
    latestAssessment: "Run 28",
    assessmentYear: "2010",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=35",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/28_35.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=35",
  },
  {
    id: "39",
    name: "CDX2",
    fullNameEn: "CDX2",
    latestAssessment: "Run 76",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=39",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/214_39.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=39",
  },
  {
    id: "20",
    name: "CEA",
    fullNameEn: "Carcinoembryonic antigen",
    latestAssessment: "Run 54",
    assessmentYear: "2018",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=20",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/105_20.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=20",
  },
  {
    id: "40",
    name: "CGA",
    fullNameEn: "Chromogranin A",
    latestAssessment: "Run 70",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=40",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/187_40.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=40",
  },
  {
    id: "85",
    name: "CK-PAN",
    fullNameEn: "Pan Cytokeratin",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=85",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_85.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=85",
  },
  {
    id: "89",
    name: "CK19",
    fullNameEn: "Cytokeratin 19",
    latestAssessment: "Run 50",
    assessmentYear: "2017",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=89",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/89_89.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=89",
  },
  {
    id: "79",
    name: "CK20",
    fullNameEn: "Cytokeratin 20",
    latestAssessment: "Run 62",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=79",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/146_79.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=79",
  },
  {
    id: "95",
    name: "CK5",
    fullNameEn: "Cytokeratin 5",
    latestAssessment: "Run 76",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=95",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/214_95.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=95",
  },
  {
    id: "88",
    name: "CK7",
    fullNameEn: "Cytokeratin 7",
    latestAssessment: "Run 62",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=88",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/146_88.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=88",
  },
  {
    id: "99",
    name: "CK8/18",
    fullNameEn: "Cytokeratin 8/18",
    latestAssessment: "Run 69",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=99",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/173_99.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=99",
  },
  {
    id: "123",
    name: "CLDN18.2",
    fullNameEn: "Claudin 18.2",
    latestAssessment: "Run C19",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=123",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/225_123.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=123",
  },
  {
    id: "122",
    name: "CLDN4",
    fullNameEn: "Claudin 4",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=122",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_122.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=122",
  },
  {
    id: "41",
    name: "CyD1",
    fullNameEn: "Cyclin D1",
    latestAssessment: "Run 75",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=41",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/205_41.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=41",
  },
  {
    id: "42",
    name: "DES",
    fullNameEn: "Desmin",
    latestAssessment: "Run 64",
    assessmentYear: "2022",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=42",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/158_42.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=42",
  },
  {
    id: "7",
    name: "DOG1",
    fullNameEn: "Discovered On GIST-1",
    latestAssessment: "Run 44",
    assessmentYear: "2015",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=7",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/44_7.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=7",
  },
  {
    id: "43",
    name: "ECAD",
    fullNameEn: "E-cadherin",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=43",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_43.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=43",
  },
  {
    id: "45",
    name: "EMA",
    fullNameEn: "Epithelial Membrane Antigen",
    latestAssessment: "Run 77",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=45",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/217_45.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=45",
  },
  {
    id: "44",
    name: "EpCAM",
    fullNameEn: "Epithelial cell-cell adhesion molecule",
    latestAssessment: "Run 69",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=44",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/173_44.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=44",
  },
  {
    id: "2",
    name: "ER",
    fullNameEn: "Estrogen Receptor",
    latestAssessment: "Run B41",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=2",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/215_2.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=2",
  },
  {
    id: "101",
    name: "ERG",
    fullNameEn: "Ets-Related Gene",
    latestAssessment: "Run 50",
    assessmentYear: "2017",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=101",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/89_101.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=101",
  },
  {
    id: "124",
    name: "FOLR1",
    fullNameEn: "Folate receptor alpha",
    latestAssessment: "Run C19",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=124",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/226_124.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=124",
  },
  {
    id: "47",
    name: "FVIII",
    fullNameEn: "Factor VIII related antigen",
    latestAssessment: "Run 11",
    assessmentYear: "2004",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=47",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/11_47.pdf",
  },
  {
    id: "8",
    name: "GATA3",
    fullNameEn: "GATA3",
    latestAssessment: "Run 73",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=8",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/201_8.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=8",
  },
  {
    id: "49",
    name: "GCDFP",
    fullNameEn: "Gross cystic disease fluid protein-15",
    latestAssessment: "Run 36",
    assessmentYear: "2012",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=49",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/36_49.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=49",
  },
  {
    id: "50",
    name: "GFAP",
    fullNameEn: "Glial fibrillary acidic protein",
    latestAssessment: "Run 13",
    assessmentYear: "2005",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=50",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/13_50.pdf",
  },
  {
    id: "48",
    name: "GPC3",
    fullNameEn: "Glypican 3",
    latestAssessment: "Run 42",
    assessmentYear: "2014",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=48",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/42_48.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=48",
  },
  {
    id: "51",
    name: "HCG",
    fullNameEn: "Human chorionic gonadotropin",
    latestAssessment: "Run 11",
    assessmentYear: "2004",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=51",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/11_51.pdf",
  },
  {
    id: "46",
    name: "HEPA",
    fullNameEn: "Hepatocyte antigen",
    latestAssessment: "Run 36",
    assessmentYear: "2012",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=46",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/36_46.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=46",
  },
  {
    id: "11",
    name: "HER2 IHC",
    fullNameEn: "HER2 IHC",
    latestAssessment: "Run B41",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=11",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/215_11.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=11",
  },
  {
    id: "12",
    name: "HER2 ISH",
    fullNameEn: "HER2 ISH",
    latestAssessment: "Run H29",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=12",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/216_12.pdf",
  },
  {
    id: "92",
    name: "IgK",
    fullNameEn: "Immunoglobulin Kappa",
    latestAssessment: "Run 23",
    assessmentYear: "2008",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=92",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/23_92.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=92",
  },
  {
    id: "93",
    name: "IgL",
    fullNameEn: "Immunoglobulin Lambda",
    latestAssessment: "Run 15",
    assessmentYear: "2005",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=93",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/15_93.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=93",
  },
  {
    id: "91",
    name: "IgM",
    fullNameEn: "Immunoglobulin M",
    latestAssessment: "Run 39",
    assessmentYear: "2013",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=91",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/39_91.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=91",
  },
  {
    id: "120",
    name: "INSM1",
    fullNameEn: "Insulinoma-associated protein 1",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=120",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_120.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=120",
  },
  {
    id: "1",
    name: "Ki67",
    fullNameEn: "Ki67",
    latestAssessment: "Run 72",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=1",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/189_1.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=1",
  },
  {
    id: "52",
    name: "MAMGLO",
    fullNameEn: "Mammaglobin",
    latestAssessment: "Run 25",
    assessmentYear: "2009",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=52",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/25_52.pdf",
  },
  {
    id: "53",
    name: "MLA",
    fullNameEn: "Melan-A",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=53",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_53.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=53",
  },
  {
    id: "81",
    name: "MLH1",
    fullNameEn: "Mismatch repair protein MLH1",
    latestAssessment: "Run 76",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=81",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/214_81.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=81",
  },
  {
    id: "54",
    name: "MSA",
    fullNameEn: "Melanosome specific antigen (HMB-45)",
    latestAssessment: "Run 40",
    assessmentYear: "2014",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=54",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/40_54.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=54",
  },
  {
    id: "82",
    name: "MSH2",
    fullNameEn: "Mismatch repair protein MSH2",
    latestAssessment: "Run 77",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=82",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/217_82.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=82",
  },
  {
    id: "83",
    name: "MSH6",
    fullNameEn: "Mismatch repair protein MSH6",
    latestAssessment: "Run 72",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=83",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/189_83.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=83",
  },
  {
    id: "55",
    name: "MUM1",
    fullNameEn: "MUM1/IRF4",
    latestAssessment: "Run 77",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=55",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/217_55.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=55",
  },
  {
    id: "9",
    name: "Napsin A",
    fullNameEn: "Napsin A",
    latestAssessment: "Run 66",
    assessmentYear: "2022",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=9",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/163_9.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=9",
  },
  {
    id: "57",
    name: "NFP",
    fullNameEn: "Neurofilament protein",
    latestAssessment: "Run 18",
    assessmentYear: "2006",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=57",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/18_57.pdf",
  },
  {
    id: "100",
    name: "NKX3.1",
    fullNameEn: "Homeobox protein Nkx-3.1",
    latestAssessment: "Run 77",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=100",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/217_100.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=100",
  },
  {
    id: "58",
    name: "OCT3/4",
    fullNameEn: "Octamer transcription factor-3/4",
    latestAssessment: "Run 53",
    assessmentYear: "2018",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=58",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/104_58.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=58",
  },
  {
    id: "59",
    name: "p16",
    fullNameEn: "p16",
    latestAssessment: "Run 72",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=59",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/189_59.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=59",
  },
  {
    id: "10",
    name: "p40",
    fullNameEn: "p40",
    latestAssessment: "Run 74",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=10",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/204_10.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=10",
  },
  {
    id: "70",
    name: "P501S",
    fullNameEn: "Prostein",
    latestAssessment: "Run 27",
    assessmentYear: "2009",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=70",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/27_70.pdf",
  },
  {
    id: "60",
    name: "p53",
    fullNameEn: "p53",
    latestAssessment: "Run 70",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=60",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/187_60.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=60",
  },
  {
    id: "61",
    name: "p57",
    fullNameEn: "p57",
    latestAssessment: "Run 41",
    assessmentYear: "2014",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=61",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/41_61.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=61",
  },
  {
    id: "62",
    name: "p63",
    fullNameEn: "p63 protein",
    latestAssessment: "Run 61",
    assessmentYear: "2021",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=62",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/145_62.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=62",
  },
  {
    id: "69",
    name: "PAP",
    fullNameEn: "Prostatic acid phosphatase",
    latestAssessment: "Run 12",
    assessmentYear: "2004",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=69",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/12_69.pdf",
  },
  {
    id: "63",
    name: "PAX2",
    fullNameEn: "Paired box gene-2 protein",
    latestAssessment: "Run 34",
    assessmentYear: "2012",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=63",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/34_63.pdf",
  },
  {
    id: "15",
    name: "PAX5",
    fullNameEn: "BSAP",
    latestAssessment: "Run 76",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=15",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/214_15.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=15",
  },
  {
    id: "64",
    name: "PAX8",
    fullNameEn: "Paired box gene-8 protein",
    latestAssessment: "Run 77",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=64",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/217_64.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=64",
  },
  {
    id: "111",
    name: "PD-L1 (IC)",
    fullNameEn: "Programmed Death Ligand 1",
    latestAssessment: "Run C16",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=111",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/195_111.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=111",
  },
  {
    id: "110",
    name: "PD-L1 (TPS/CPS)",
    fullNameEn: "Programmed Death Ligand 1",
    latestAssessment: "Run C19",
    assessmentYear: "2026",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=110",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/218_110.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=110",
  },
  {
    id: "65",
    name: "PLAP",
    fullNameEn: "Placental Alkaline Phosphatase",
    latestAssessment: "Run 35",
    assessmentYear: "2012",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=65",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/35_65.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=65",
  },
  {
    id: "84",
    name: "PMS2",
    fullNameEn: "Mismatch Repair Protein PMS2",
    latestAssessment: "Run 71",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=84",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/188_84.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=84",
  },
  {
    id: "66",
    name: "Podop",
    fullNameEn: "Podoplanin",
    latestAssessment: "Run 75",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=66",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/205_66.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=66",
  },
  {
    id: "67",
    name: "PR",
    fullNameEn: "Progesterone Receptor",
    latestAssessment: "Run B39",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=67",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/203_67.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=67",
  },
  {
    id: "119",
    name: "PRAME",
    fullNameEn: "PReferentially expressed Antigen in MElanoma",
    latestAssessment: "Run 70",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=119",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/187_119.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=119",
  },
  {
    id: "68",
    name: "PSA",
    fullNameEn: "Prostate-specific antigen",
    latestAssessment: "Run 69",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=68",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/173_68.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=68",
  },
  {
    id: "71",
    name: "S100",
    fullNameEn: "S-100 protein",
    latestAssessment: "Run 59",
    assessmentYear: "2020",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=71",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/134_71.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=71",
  },
  {
    id: "72",
    name: "SALL4",
    fullNameEn: "Sal-like protein 4",
    latestAssessment: "Run 43",
    assessmentYear: "2015",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=72",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/43_72.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=72",
  },
  {
    id: "108",
    name: "SATB2",
    fullNameEn: "SATB2",
    latestAssessment: "Run 75",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=108",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/205_108.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=108",
  },
  {
    id: "105",
    name: "Smad4",
    fullNameEn: "Smad4",
    latestAssessment: "Run 57",
    assessmentYear: "2019",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=105",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/122_105.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=105",
  },
  {
    id: "56",
    name: "SMH",
    fullNameEn: "Myosin, smooth muscle heavy chain",
    latestAssessment: "Run 66",
    assessmentYear: "2022",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=56",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/163_56.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=56",
  },
  {
    id: "94",
    name: "SOX10",
    fullNameEn: "Transcription factor SOX-10",
    latestAssessment: "Run 75",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=94",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/205_94.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=94",
  },
  {
    id: "97",
    name: "SOX11",
    fullNameEn: "Transcription factor SOX-11",
    latestAssessment: "Run 47",
    assessmentYear: "2016",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=97",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/82_97.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=97",
  },
  {
    id: "73",
    name: "SYP",
    fullNameEn: "Synaptophysin",
    latestAssessment: "Run 73",
    assessmentYear: "2025",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=73",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/201_73.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=73",
  },
  {
    id: "74",
    name: "TdT",
    fullNameEn: "Terminal deoxynucleotidyl transferase",
    latestAssessment: "Run 52",
    assessmentYear: "2018",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=74",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/101_74.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=74",
  },
  {
    id: "121",
    name: "TRPS1",
    fullNameEn: "TRPS1",
    latestAssessment: "Run 72",
    assessmentYear: "2024",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=121",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/189_121.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=121",
  },
  {
    id: "75",
    name: "TTF1",
    fullNameEn: "Thyroid transcription factor-1",
    latestAssessment: "Run 68",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=75",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/172_75.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=75",
  },
  {
    id: "112",
    name: "URO II/III",
    fullNameEn: "Uroplakin II/III",
    latestAssessment: "Run 68",
    assessmentYear: "2023",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=112",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/172_112.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=112",
  },
  {
    id: "76",
    name: "VIM",
    fullNameEn: "Vimentin",
    latestAssessment: "Run 52",
    assessmentYear: "2018",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=76",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/101_76.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=76",
  },
  {
    id: "77",
    name: "WT1",
    fullNameEn: "Wilms tumour-1 protein",
    latestAssessment: "Run 55",
    assessmentYear: "2019",
    sourceUrl: "https://www.nordiqc.org/epitope.php?id=77",
    reportUrl: "https://www.nordiqc.org/downloads/assessments/117_77.pdf",
    protocolUrl: "https://www.nordiqc.org/recommended.php?epitope_id=77",
  }
]
